# Generated by rust2rpm 27
%bcond check 1
%global debug_package %{nil}

%global crate testing_table

Name:           rust-testing_table
Version:        0.3.0
Release:        1%{?dist}
Summary:        An easy to use library for pretty print tables of Rust `struct`s and `enum`s.

License:        MIT
URL:            https://crates.io/crates/testing_table
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
A library which provides handy macros for table testing.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE-MIT
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+std-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+std-devel %{_description}

This package contains library source intended for building other packages which
use the "std" feature of the "%{crate}" crate.

%files       -n %{name}+std-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+ansi-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+ansi-devel %{_description}

This package contains library source intended for building other packages which
use the "ansi" feature of the "%{crate}" crate.

%files       -n %{name}+ansi-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+ansitok-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+ansitok-devel %{_description}

This package contains library source intended for building other packages which
use the "ansitok" feature of the "%{crate}" crate.

%files       -n %{name}+ansitok-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Mon May 05 2025 mschae23 <pkg@mschae23.de> - 0.3.0-1
- Initial package
