# Generated by rust2rpm 27
%bcond check 1
%global debug_package %{nil}

%global crate tabled

Name:           rust-tabled
Version:        0.19.0
Release:        1%{?dist}
Summary:        An easy to use library for pretty print tables of Rust `struct`s and `enum`s

License:        MIT
URL:            https://crates.io/crates/tabled
Source:         %{crates_source}

# Some paths in the crate's examples assume it is in the original directory structure as in the source code repository;
# this patch fixes that to make them compile
Patch:          0001-example-paths.patch

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
An easy to use library for pretty printing tables of Rust `struct`s and `enum`s.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE-MIT
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+std-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+std-devel %{_description}

This package contains library source intended for building other packages which
use the "std" feature of the "%{crate}" crate.

%files       -n %{name}+std-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+derive-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+derive-devel %{_description}

This package contains library source intended for building other packages which
use the "derive" feature of the "%{crate}" crate.

%files       -n %{name}+derive-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+ansi-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+ansi-devel %{_description}

This package contains library source intended for building other packages which
use the "ansi" feature of the "%{crate}" crate.

%files       -n %{name}+ansi-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+macros-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+macros-devel %{_description}

This package contains library source intended for building other packages which
use the "macros" feature of the "%{crate}" crate.

%files       -n %{name}+macros-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+assert-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+assert-devel %{_description}

This package contains library source intended for building other packages which
use the "assert" feature of the "%{crate}" crate.

%files       -n %{name}+assert-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+ansi-str-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+ansi-str-devel %{_description}

This package contains library source intended for building other packages which
use the "ansi-str" feature of the "%{crate}" crate.

%files       -n %{name}+ansi-str-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+ansitok-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+ansitok-devel %{_description}

This package contains library source intended for building other packages which
use the "ansitok" feature of the "%{crate}" crate.

%files       -n %{name}+ansitok-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+tabled_derive-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+tabled_derive-devel %{_description}

This package contains library source intended for building other packages which
use the "tabled_derive" feature of the "%{crate}" crate.

%files       -n %{name}+tabled_derive-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+testing_table-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+testing_table-devel %{_description}

This package contains library source intended for building other packages which
use the "testing_table" feature of the "%{crate}" crate.

%files       -n %{name}+testing_table-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Mon May 05 2025 mschae23 <pkg@mschae23.de> - 0.19.0-1
- Update to 0.19.0

* Sun Nov 24 2024 mschae23 <pkg@mschae23.de> - 0.17.0-1
- Update to 0.17.0

* Sun Nov 24 2024 mschae23 <pkg@mschae23.de> - 0.16.0-2
- Rebuild for changed package signing key

* Wed Nov 20 2024 mschae23 <pkg@mschae23.de> - 0.16.0-1
- Initial package
