# Generated by rust2rpm 27
%bcond check 1
%global debug_package %{nil}

%global crate tabled_derive

Name:           rust-tabled_derive
Version:        0.11.0
Release:        1%{?dist}
Summary:        Derive macros which is used by tabled crate

License:        MIT
URL:            https://crates.io/crates/tabled_derive
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Derive macros which is used by tabled crate.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE-MIT
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Mon May 05 2025 mschae23 <pkg@mschae23.de> - 0.11.0-1
- Initial package
