# Generated by rust2rpm 26
%bcond_without check
%global debug_package %{nil}

%global crate error_handling

%global project_name DeArrowBrowser
%global source_commit c8cf5fbb2a0da4118acc1f0bb60a768d4ca5321f

Name:           rust-error-handling
Version:        1.13.0
Release:        %autorelease
Summary:        The core of anyhow, written from scratch to make errors cloneable

SourceLicense:  AGPL-3.0-only
License:        AGPL-3.0-only
# LICENSE.dependencies contains a full license breakdown

URL:            https://github.com/mini-bomba/DeArrowBrowser/tree/master/error_handling
Source:         https://github.com/mini-bomba/DeArrowBrowser/archive/%{source_commit}.tar.gz

Patch:          0001-inline-workspace.patch

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
%{summary}.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{project_name}-%{source_commit} -p1
# Workspace build; only build with relevant subdirectory
cd ..
%{__mv} %{project_name}-%{source_commit}/%{crate} tmp-main
%{__rm} -rf %{project_name}-%{source_commit}
%{__mv} tmp-main %{project_name}-%{source_commit} # the directory has to be called this, because %%setup sets this as buildsubdir
cd %{project_name}-%{source_commit}

%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build
%{cargo_license_summary}
%{cargo_license} > LICENSE.dependencies

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
