# Generated by rust2rpm 26
%bcond_without check
%global debug_package %{nil}

%global crate proc-macro-error2

Name:           rust-proc-macro-error2
Version:        2.0.1
Release:        1%{?dist}
Summary:        Almost drop-in replacement to panics in proc-macros

License:        MIT OR Apache-2.0
# LICENSE.dependencies contains a full license breakdown

URL:            https://github.com/GnomedDev/proc-macro-error-2
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
This crate aims to make error reporting in proc-macros simple and easy to use. Migrate from panic!-based errors for as little effort as possible!}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE-APACHE
%license %{crate_instdir}/LICENSE-MIT
%doc %{crate_instdir}/README.md
%doc %{crate_instdir}/CHANGELOG.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+syn-error-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+syn-error-devel %{_description}

This package contains library source intended for building other packages which
use the "syn-error" feature of the "%{crate}" crate.

%files       -n %{name}+syn-error-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build
%{cargo_license_summary}
%{cargo_license} > LICENSE.dependencies

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Sun Nov 24 2024 mschae23 <pkg@mschae23.de> - 2.0.1-1
- Initial package

